# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "23268fb349eeef9cb314894e46151bb1"
name = "dev test2"
handle = "dev-test2-3"
application_url = "https://tap-firmware-conference-logos.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "starting-to-build-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://tap-firmware-conference-logos.trycloudflare.com/auth/callback",
  "https://tap-firmware-conference-logos.trycloudflare.com/auth/shopify/callback",
  "https://tap-firmware-conference-logos.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
